language: java
deploy:
  provider: releases
  api_key:
    secure: OQzejB+ztML1lboZCUgUTHRaSFw8JtenjsWStT371dsH0HG9XG+mO+nG2sglhLF4vT5vIH3O0uQqZ879NMUMNO5z9fK0izZl6tQ282ts7HRHvdUxQSB3WJiu+9ZNc4xAIeYbNE5JGfk0G0ap7hrgfnG5QRbUDR3nKABR6bkZ+8ywhp61/gkMpgqtivpGVb3pU3LOtisOqEPwUY+JsT0ISQK5f4TUTfyBU8U3Tjmtet1UAirhxpGQdj2DdOk7oRNfsSPu2WlyT43HeQS8v7SyDMw47rir5Cr1BKJR6tqJKT+8VJhLVer1xwfEF95w2P2c7Pj+dtW789m2eCr3AX2KU7BJGpHj50rSRKz/ldH23NjpNfzXTqJSVyFFahqemBxTAer6JCk8MVRnSUTcfSqhuKlNkQz53Flc/vjwpnsPLq+Jph3p6mtz3srynbHbdZDOC036nnoHSxaGwm/heHgsKRPNq7wLkxpLlRH+0q/fqjNZNdcMKUb7IbD7T1bvUAHYtsjVaYnhwrR9wFi8n/JDEO1QSQVt8ICPhC3LbcWe6Q8tYzO+Z/H+0VuOCFfJsUCKIoyfgIONis8bB7v1ldXjM9pu7p0WPPy4VY4TO4PRdAqy5xQuJmDsmgjmPge9IzeuCl6FDie66uLlvk1/4RKREqxFq6SFTSUNXTMzf3lDLv4=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-travisci-plugin
notifications:
  slack:
    secure: bGSiUDDDKargLjGgvqUoVQRFo5vk9i1iL4BxbHVlLJWyo+i/UPCD3+YN4I0gUlILYIRs4g2yg8g4sV7RrIoUkJYuj+TL2h+qJgkO7y2DtZ71Bue/0g6z1DoX4IxjcPt9i/0i0VA5Cw3Nj2bZm0VFSfH4eMb/Nj4AGqKwbDdVQkcZdaXBWKqaFdulMJ9nBlzJeZwZ5UEUhCew59uo3ybJawl03G65L/1b8Lv8bN2D3B+JReKvizaibOrUsl04MhWK03zw9gFT9vPVxvMg7rkVNHrlj82L/upNRwfWwD6U4f44gpQvAofL99go3Gt0tD3amDapV3qvDncD1Zm28ME2VvqTkoMkeuHU5jrhrH9fWLuaBBmixZ/mhgrYr3afnMZmOCSKzdrvQj+OLqTCNcXhX6TTn1zWnfozxr/QI+BklTikqHQiAsbArhXhq597TbIU9x56Ij8su7Si0RPgmFODv85SJ/B84z3LKvqhBGTdKGo+YbE60xaTGrLAOYvJoCxg3AHa6yYDjug7JOZfRXrncKTF4VpFmqhWgkMPnk0WVZcJL2WXNFeIzQMQd4wj7pcUchFulfAJRBi1UwTk+5npv/3an4UzsvQCVVYyyZIjMVrfWhoL2dCQaANdIRkwVOJltGy71QU623kLfmdnzBK49c2WqMQjn9TQ/K389PowlF8=
