language: java
deploy:
  provider: releases
  api_key:
    secure: H1wfikNc0/s8NXDGqWH9JDgA0TsLdtZ1Wbvn9b2LFOBjSnRj4rJyvwSm/6iXMq9iFK7N9RDI4jzffnPqTfPwsr97I787jkoeUkgU4chH9AWWyv8dNhWlsuU0V3mOYAwpuZ6BXOlvSzcYdAFAY0HYtGIQyHSVLI4oGuSB22LcIu26STZl6NVlrqzDUyoSBlvRzKlhNRMllPKzQTrxqDrnxUtSdg3b1I/BJvt4h4gQywpbdMzc3pI6rYoHWVFgnWA1ZkuMsAhFNzm7DVoh53QCxiHsocRhZcvzxQ/OpdNnheGL8sMLt7+JBEMcVkKueGLfePb5WT5AQlGMMR+bmoBgWtzznbMkkqSdeRJw6fuzLOu20O9bWg7bWaNyFoIQA3lO6RWbx/INO5tc++jOfcdkOmPH1//IQM8ZokV91qp4TJGiUV4GnTZEuav6bivCLmbge05OWpSioBYGfsVNwjxEmM3QcePZuAoOfuq7Fi38+/ykRBL714BkWspSHkuwrtgOk0/66CCoTpymc/VvJxqKL6l2QrBX56NZpGzrmF6GOfqihF/fPZPYKqnFIFIXVYTVYShnuhgvHWrReielR6ywPH4hYjhoVW9Uu0MgbD0Yxqqg/UUKuPxQpTRYtgk+JN4LrMgdT9iXpscfnA6MunvquFkJftL0LHo0jQQF+1FAw9M=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-travisci-plugin
notifications:
  hipchat:
    rooms:
      secure: Ne0/J9sDiLIm7kPIWVzXLQKvY3/qXRBbe6l3O3L+s3GuR0qkkWkpM9X6TR8+ICcWD462E2+tOE0HR9hnlipKAVsDYJiNh3/CEMLT7eqeWeHqwIIAP7uo+Xudyzny1zyRGYCuXnmL3hQIBLXxoA0jDFDQVt04mN3eqdH/Ta9+MUlHCGwVnz2X+HzFF5dbTWlCU087irv33p093A2T0v5Ou5JB6Vhb/nDyRSOvaWqDzEin5j/scz97KucxzSxZDVRiz6oTnIbBtmtvCzFTqgWqYCW9RBvJ2HnjaucuPp/doyaS1nlkuWdkDgffv+FwI4QZ/vjmDGlcayo5K11P7WXW/dLQYtXORc+PNFHJKvWqfMePtfw9FyXVwwS4oL0j+EcJTEJMBjzna1v4ioRdDsbKB/xwkPegtOgGM/KVHmWB2uM0Z3pg3dAejCBcftZZYgvkyuHAO87Y47RM+93Uym+spzoGJzH1fDbe8qBd8vnyk80hUzqbNSfoBadOlZMyVMsB39V0loy607R/b7syhaUoWQ5imFMI0vOaK30cADw+PxSwTZyg9ImzNLXXmEE7noQsMbOymCiyLMla4zmEAXKPMWSehGJfQOU/0IRRmVb+0aR3U0Gpw83TAJKN9Sjs38GvhASvr5N4AJDbc13Q6T9ZUFUvZlQgzkijdsM8vjD20NA=
