language: java
notifications:
  hipchat:
    rooms:
      secure: gmf1OZkC8SJdj5u1SZoGeDMheC91jbva3XBGkg2f0c4yZd5lRrpLpct4mb/Bly1akmkhITam7xZ2RipT9JHzlvOrroZDyLvaZZBVRkV92wFahGnj3xjqZ/jrRU6aw+M3F0BxD6OiSTd7pqAV+ygJi/U5qNKeSnjJITlsYOJ5tdWPrzqA4LlRGFGtn+aJd9rm33ZN0Q5oxN20pJFPyisA62dHQzQp+/oklmt6es5fnifAd4GU4K0AelwbO9Yald+extbXOIszFkNKxLmlQ6L2okPcgmKviM3dOsNH0cyuHCH7AIdgGGQy6cPFEJkEdX+5hAtTrq4M/HQcy/YlcNiRyKfMvIsb3d+3SikcdxuInHqC35Wf2Nb/aWmf8Xg9U9GNTKf5XsM+8GJQE48m1qgKeHA/nqDvWT7FmK9LrqHfAFYhu1INxn3rRLLwXJZgqR3DU7rRLtJnXow17woz+rHhk3prcvmehoGlGBR2SrJr9w46djCekaR+XLO2cPJ/CSVhZg0YLGxg2Il/ents08lbiPdhgUfC3x4nVokXvBh9SkiPRZdmTVJH9fTUN2Mn897TJMDthfDz03Y/oFDnSa8uGKEIefl5Lj34dUuHNPr9HX7rVgJre07UClzvWdNY1ZKIp07DQsfg6iPpsUvRJR0x7nKENun9PawWrAcuKhlJL1c=
      notify: true
deploy:
  provider: releases
  api_key:
    secure: H1wfikNc0/s8NXDGqWH9JDgA0TsLdtZ1Wbvn9b2LFOBjSnRj4rJyvwSm/6iXMq9iFK7N9RDI4jzffnPqTfPwsr97I787jkoeUkgU4chH9AWWyv8dNhWlsuU0V3mOYAwpuZ6BXOlvSzcYdAFAY0HYtGIQyHSVLI4oGuSB22LcIu26STZl6NVlrqzDUyoSBlvRzKlhNRMllPKzQTrxqDrnxUtSdg3b1I/BJvt4h4gQywpbdMzc3pI6rYoHWVFgnWA1ZkuMsAhFNzm7DVoh53QCxiHsocRhZcvzxQ/OpdNnheGL8sMLt7+JBEMcVkKueGLfePb5WT5AQlGMMR+bmoBgWtzznbMkkqSdeRJw6fuzLOu20O9bWg7bWaNyFoIQA3lO6RWbx/INO5tc++jOfcdkOmPH1//IQM8ZokV91qp4TJGiUV4GnTZEuav6bivCLmbge05OWpSioBYGfsVNwjxEmM3QcePZuAoOfuq7Fi38+/ykRBL714BkWspSHkuwrtgOk0/66CCoTpymc/VvJxqKL6l2QrBX56NZpGzrmF6GOfqihF/fPZPYKqnFIFIXVYTVYShnuhgvHWrReielR6ywPH4hYjhoVW9Uu0MgbD0Yxqqg/UUKuPxQpTRYtgk+JN4LrMgdT9iXpscfnA6MunvquFkJftL0LHo0jQQF+1FAw9M=
  file: build/libs/xlr-travisci-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-travisci-plugin
