language: java
deploy:
  provider: releases
  api_key:
    secure: OQzejB+ztML1lboZCUgUTHRaSFw8JtenjsWStT371dsH0HG9XG+mO+nG2sglhLF4vT5vIH3O0uQqZ879NMUMNO5z9fK0izZl6tQ282ts7HRHvdUxQSB3WJiu+9ZNc4xAIeYbNE5JGfk0G0ap7hrgfnG5QRbUDR3nKABR6bkZ+8ywhp61/gkMpgqtivpGVb3pU3LOtisOqEPwUY+JsT0ISQK5f4TUTfyBU8U3Tjmtet1UAirhxpGQdj2DdOk7oRNfsSPu2WlyT43HeQS8v7SyDMw47rir5Cr1BKJR6tqJKT+8VJhLVer1xwfEF95w2P2c7Pj+dtW789m2eCr3AX2KU7BJGpHj50rSRKz/ldH23NjpNfzXTqJSVyFFahqemBxTAer6JCk8MVRnSUTcfSqhuKlNkQz53Flc/vjwpnsPLq+Jph3p6mtz3srynbHbdZDOC036nnoHSxaGwm/heHgsKRPNq7wLkxpLlRH+0q/fqjNZNdcMKUb7IbD7T1bvUAHYtsjVaYnhwrR9wFi8n/JDEO1QSQVt8ICPhC3LbcWe6Q8tYzO+Z/H+0VuOCFfJsUCKIoyfgIONis8bB7v1ldXjM9pu7p0WPPy4VY4TO4PRdAqy5xQuJmDsmgjmPge9IzeuCl6FDie66uLlvk1/4RKREqxFq6SFTSUNXTMzf3lDLv4=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-travisci-plugin
notifications:
  hipchat:
    rooms:
      secure: Ne0/J9sDiLIm7kPIWVzXLQKvY3/qXRBbe6l3O3L+s3GuR0qkkWkpM9X6TR8+ICcWD462E2+tOE0HR9hnlipKAVsDYJiNh3/CEMLT7eqeWeHqwIIAP7uo+Xudyzny1zyRGYCuXnmL3hQIBLXxoA0jDFDQVt04mN3eqdH/Ta9+MUlHCGwVnz2X+HzFF5dbTWlCU087irv33p093A2T0v5Ou5JB6Vhb/nDyRSOvaWqDzEin5j/scz97KucxzSxZDVRiz6oTnIbBtmtvCzFTqgWqYCW9RBvJ2HnjaucuPp/doyaS1nlkuWdkDgffv+FwI4QZ/vjmDGlcayo5K11P7WXW/dLQYtXORc+PNFHJKvWqfMePtfw9FyXVwwS4oL0j+EcJTEJMBjzna1v4ioRdDsbKB/xwkPegtOgGM/KVHmWB2uM0Z3pg3dAejCBcftZZYgvkyuHAO87Y47RM+93Uym+spzoGJzH1fDbe8qBd8vnyk80hUzqbNSfoBadOlZMyVMsB39V0loy607R/b7syhaUoWQ5imFMI0vOaK30cADw+PxSwTZyg9ImzNLXXmEE7noQsMbOymCiyLMla4zmEAXKPMWSehGJfQOU/0IRRmVb+0aR3U0Gpw83TAJKN9Sjs38GvhASvr5N4AJDbc13Q6T9ZUFUvZlQgzkijdsM8vjD20NA=
